### ISSUE TITLE
Better Rocker webpack configuration naming

### ISSUE THREAD

**Issue by mkrauskopf** [lastui/rocker#419]
The user-level webpack configuration file should be named `webpack.rocker.js`. instead of `webpack.config.js`. As such it will be clearer that the file is used (required) by the Rocker and it will not clash with potential other user webpack configurations.

Here: https://github.com/lastui/rocker/blob/main/bin/webpack.js#L150

**Comment by jancajthaml** [comment]
> As such it will be clearer that the file is used (required)
then the name should be `rocker.config.js` instead

> it will not clash with potential other user webpack configurations.
there should be no other webpack configurations and instances

**Comment by jancajthaml** [comment]
rocker now includes `cli`

**Comment by jancajthaml** [comment]
webpack.config.js is not optional in projects. If there is no webpack.config.js the module one will be used.

This is currently MVP implementation, in future code analysis and code scanning will be used to determine what the project actually is, if its a module or spa and based on that proper config will be provided as a default.

As for now not providing webpack.config.js in your project will result in project being bundled as a module.

**Comment by jancajthaml** [comment]
will close the issue now. I will not introduce `rocker.config.js` convention right now, we can revisit this later.

**Comment by mkrauskopf** [comment]
Nice 👍🏽. Will check it out! Thanks.
