### ISSUE TITLE
Type checking for TypeScript code-base

### ISSUE THREAD

**Issue by mkrauskopf** [lastui/rocker#435]
After implementing basic TS support in #427, it is possible to use `.ts` files - so TS is supported in the opinionated core.

As the next step, it would be nice to have support also for the real type-checking during the transpile time. Such that `rocker build` would fail if the code, according to the `tsconfig.json`, is wrongly typed. Or alternatively `rocker type-check` or something alike.

**Comment by mkrauskopf** [comment]
Or at least provide a sample/documentation explaining how to handle this. E.g. using `tsc --noEmit` similarly to this mkrauskopf/computations-rocker@30d9b08.

**Comment by jancajthaml** [comment]
I just found out that babel-loader (and webpack generally) does not do semantic checking, just trans-piling.

In the light of this I will switch from babel-loader and linaria-webpack-loader to ts-loader.

And support only ts+tsx extensions (not js/jsx) this was not true with legacy bundlers like grunt/gulp so this was a shock to me.

For this I'd need a hand to first type rocker sources and migrate everything to typescript with current setup, before switching fully to ts.

Would you be able to help with that effort @mkrauskopf ?

**Comment by mkrauskopf** [comment]
Rocker has `emitOnErrors: true`. Could it be related?

See https://webpack.js.org/configuration/optimization/#optimizationemitonerrors

**Comment by jancajthaml** [comment]
no sadly 👎

**Comment by mkrauskopf** [comment]
> Would you be able to help with that effort @mkrauskopf ?

Depends. Let's coordinate on that via IM.
