### ISSUE TITLE
Specify the requirements for the Node engine

### ISSUE THREAD

**Issue by mkrausko-cisco** [lastui/rocker#817]
The `npm ci` fails with older Node engines:

```bash
$ npm --version; node --version
6.14.15
v14.17.6
```

Consider specifying the minimum engine version in the package.json#engines section and/or make it strict via `.npmrc`.

**Comment by jancajthaml** [comment]
```
"engines": {
    "node": ">=20.0.0",
    "npm": ">=9.0.0"
  }
```

https://nodejs.dev/en/about/releases/

Node 20 will enter LST starting November 2023
